number=(int(input("enter a number here")))
print(number," to the power of 1", "is", number ** 1)
print(number," to the power of 2", "is", number ** 2)
print(number," to the power of 3", "is", number ** 3)
print(number," to the power of 4", "is", number ** 4)
print(number," to the power of 5", "is", number ** 5)
print(number," to the power of 6", "is", number ** 6)
print(number," to the power of 7", "is", number ** 7)
print(number," to the power of 8", "is", number ** 8)
print(number," to the power of 9", "is", number ** 9)
print(number," to the power of 10", "is", number ** 10)
print(number," to the power of 11", "is", number ** 11)
print(number," to the power of 12", "is", number ** 12)