number=(int(input("enter a number here")))
print(" 1 times,", number, "is", number * 1)
print(" 2 times,", number, "is", number * 2)
print(" 3 times,", number, "is", number * 3)
print(" 4 times,", number, "is", number * 4)
print(" 5 times,", number, "is", number * 5)
print(" 6 times,", number, "is", number * 6)
print(" 7 times,", number, "is", number * 7)
print(" 8 times,", number, "is", number * 8)
print(" 9 times,", number, "is", number * 9)
print(" 10 times,", number, "is", number * 10)
print(" 11 times,", number, "is", number * 11)
print(" 12 times,", number, "is", number * 12)